# templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    component: backend
    {{- include "imdb-clone.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 5000
    protocol: TCP
  type: {{ .Values.backend.service.type }}