# templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: imdb-clone
    component: frontend
    {{- include "imdb-clone.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    protocol: TCP
  type: {{ .Values.frontend.service.type }}